### PR TITLE
# Ruby: OOP

### PR DESCRIPTION
**Pull request by FrederickMih**

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED** 👎🏽 

**Hey @FrederickMih, a great job is done with the game so far. There are only a few issues left to meet all requirements.** 

**REQUIRED CHANGES:**

- [ ] Each players' move has a recurring bug. `1egst` will occupy index `1`. Kindly fix that.
Screenshot_2021-02-05_08-56-58

- [ ] Use `yes` to have players repeat the game and `no` or any other input to cancel the game, instead of the reverse.


- [ ] [Optional] When a player wins, would be better to include their name and let them see it. 

Make the required changes and submit for a CRR.

**Happy Coding!!** 💯 

Reach me on slack:
**Roy Mukuye**

**Review by BrianSammit — CHANGES_REQUESTED** [review]
REQUIRED CHANGES :green_circle: 
-----------------------
Hello team :wave: a great job you are doing :muscle: 
However, there are some changes to make to complete this milestone.
------------------------

- [ ] Don't use puts on your lib directory.

Screenshot from 2021-02-05 09-00-14

- [ ] The game tells me that I won, and it shouldn't.

Screenshot from 2021-02-05 09-05-41

- [ ] If a made an invalid move the game pass the turn to the next player.

Screenshot from 2021-02-05 09-09-51

- [ ] In this scenario doesn't tell me the winner. 

Screenshot from 2021-02-05 09-12-47

---------------------------
Made the required changes and send it again for review. :hammer_and_wrench: 
HAPPY CODDING!!! 

programming

**Comment by FrederickMih** [comment]
Milestone 3: Tic Tac Toe game

**Review by cristianCeamatu — CHANGES_REQUESTED** [review]
## ♻️ Changes required
#### Congratulations for your efforts! The logic was easy to follow and understand and your project works perfectly!
However, there are some small changes to be done in order to get this project approved:

### Mandatory
- [ ] Don't use puts on your lib directory, you have a `p '<<<<<-->>>> You Won! <<<<<-->>>>'` in your `play_game.rb` file. Please move it to the `main.rb`, the previous TSE also requested this change

### Optional
- [ ] Remove all the comments from the `main.rb`, this is a mandatory requirement for all projects but I will treat it as optional because the previous TSE did not mention it.

### Suggestions
1. [Optional] Validate the player name to be a string or to start with a letter, this is a great opportunity to improve your Regex skills, you will use Regex in lots of projects.
2. [Optional] Add `sleep` and colors to your game, this will totally transform your game and make it feel like it is not a simple CLI game. Links: [colors (the second answer is without using any gem)
](https://stackoverflow.com/questions/1489183/colorized-ruby-output-to-the-terminal), [sleep](https://stackoverflow.com/questions/1329967/tell-ruby-program-to-wait-some-amount-of-time) and a working example: [example](https://repl.it/@cristianCeamatu/microverse-ruby-tic-tac-toe)

## Please also check my inline comments and do the required changes then submit for another review

Don't hesitate to contact me on Slack if needed, I would be happy to join your call and help.

Best regards,
Cristian Ceamatu
Slack: Cristian Viorel Ceamatu

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @FrederickMih, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏   I appreciate your hard work. Kindly fix the following issues. 

[REQUIRED]

- [ ] Remove the .gitkeep file since you have the actual files in the folder.
- [ ] Don't use input/output statements such as puts/print/p and "gets.chomp" outside the "main.rb" file.

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUESTED ♻

### Hey, nice project so far. I noticed that you are missing some key features of this project, so we have to improve a few things before moving on:

- [ ] If I type one letter, the code doesn't return that the move is invalid;
- [ ] At the end the game doesn't display which player won, just output: "<<<<<-->>>> You Won! <<<<<-->>>>"


## As always, I wish you all the very best and see you at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

**Review by kevcap — APPROVED** [review]
# [STATUS] PROJECT APPROVED 🍾

### I really like your project! Congrats @FrederickMih, you did an excellent job, you have my approval to go ahead and merge this pull request!

⚠ I found one bug in your game, if I made the following plays, the second player will repeat his turn;
```
Player1
Player2

input: a
input: <empty> (just type enter)
input: 1
input: a
input: 2
input: a
input: a
input: 2
input: 3
input: a
input: 4 - BUG
input: 4
input: 5
```


## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

**Pull request merged**
