### PR TITLE
Code Review Request for the RSpec testing on Tic Tac Toe

### PR DESCRIPTION
**Pull request by Prabhakarzx**
### Technologies used: 
- [x]  Ruby
- [x]  Rspec

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Prabhakarzx :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the minimum requirements for this project carefully, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] You should test all of the public methods you have in the following files: `lib/board.rb`, `lib/play_game.rb`, `lib/tictactoe.rb`
- [x] Remember to test all of the cases (positive and negative cases)
- [x] Add the how to run test in readme file

# [Optional changes] :yellow_circle: 
- [ ] I would recommend you to setup the rspec for github actions, that will be very good because any visitor of your repository will be able to know the satatus of tests on your branch
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by Prabhakarzx** [comment]
# Dear @descholar-ceo, :handshake:
## Thank you for the appreciation and the detailed code review. I'm implementing the required changes. :100: 
### Thanks once again! :bouquet:

**Review by LamiaSristy — COMMENTED** [review]
Hello, @Prabhakarzx, Nice project, and please check my suggestions to get approval. :) :)

**Review by LamiaSristy — CHANGES_REQUESTED** [review]
# Status: Change Required. ♻️

Hello @Prabhakarzx  🙌 

**Thank you for making the mandatory changes the former reviewer mentioned. 👍 👍**

**A lot of effort surely went into this and you did well having wide test coverage, with positive and negative test cases. 💪**

## To Highlight: 🌟🌟 
* Your repository is professional, very nice PR message and commit messages.
*  Your test suites are very well organized.
*  Adding instructions for testing is a plus in README.

## To Improve: Let's move toward the real issue🛠️

**Currently, there are only 6 test cases, are available while you have written 12 test cases.**

**To make available all the test suits you need to change the names of 2 of your files, in the spec folder. Please check below:** 
 - [x] Rename `play_game_rspec.rb` to `play_game_spec.rb`
 - [x] Rename  `board_rspec.rb ` to `board_spec.rb` 

**Please make the changes and ask again for a CRR.**

Feel free to reach me on slack @lamiasristy 🙋

Keep up the spirit always. 👍 

Happy Coding 💻

**Comment by mimipeshy** [comment]
### STATUS :APPROVED :partying_face: 

Hey there @Prabhakarzx  :wave: :wave:  good job on working on the requested changes. This project is therefore approved. Go ahead and merge. All the best in the next milestones :man_technologist: 

Regards
Peris Ndanu

**Comment by Prabhakarzx** [comment]
## Thank You @LamiaSristy for the appreciation and valuable suggestion. :1st_place_medal: 
#### I was thinking and searching for the same but couldn't got the proper answer. And here you suggested it. Thanks! :bouquet: 

## Thank you @mimipeshy for the review and approval! :100:

**Pull request merged**
